import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Sing Up",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
      {/* <h1 className="bg-red-600">Navegação</h1> */}
        {children}
        </body>
    </html>
  );
}
