import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>)
  { 
    return(
            <>
            <h1> sublayout do dashboard</h1>
            {children}
            </>
    )
}